feat: package 구조 생성 및 dao, service interface 정의
Try-Tdd/board pull request #1
Opened 2021-07-04 15:36 UTC by Beoum

package 생성과 interface 및 관련 method 정의 진행했습니다.

2021-07-04 15:41 UTC, ohgillwhan commented
ORM을 쓸건지, Mapper를 쓸건지 아직 정해진바가 없는것 같아보이는데, 어떤것을 쓸건지 답글좀 주십숑

2021-07-04 15:46 UTC, Beoum commented
ORM 사용 예정이고 그에 따라서 학습 진행중입니다!

2021-07-04 15:46 UTC, Beoum commented
> ORM을 쓸건지, Mapper를 쓸건지 아직 정해진바가 없는것 같아보이는데, 어떤것을 쓸건지 답글좀 주십숑

ORM 사용 예정이고 그에 따라서 학습 진행중입니다!

2021-07-05 03:24 UTC, wook87 requested changes
코멘트 남긴부분 확인부탁드립니다.

2021-07-05 03:24 UTC, wook87 commented on src/main/java/com/board/tddboard/dao/BoardDao.java
> +    public void updateById(Long id);
```suggestion
    public void removeById(Long id);
    public void updateById(Long id);
```

삭제나 수정이후 `void` 로 리턴하는 것보다 `int` 나 `boolean` 으로 리턴해서 유효성 확인까지 하는건 어떨까요

2021-07-05 03:24 UTC, wook87 commented on src/main/java/com/board/tddboard/domain/Board.java
> +@Data
`@Data` 는 필요없는 부분까지 너무 많이 붙어있어서 필요한것만 경량해서 쓰시는게 어떨까요

2021-07-05 03:24 UTC, wook87 commented on src/main/java/com/board/tddboard/domain/Comment.java
> +@Data
@Data 는 필요없는 부분까지 너무 많이 붙어있어서 필요한것만 경량해서 쓰시는게 어떨까요

2021-07-05 14:09 UTC, Beoum commented on src/main/java/com/board/tddboard/domain/Board.java
> +@Data
@Data anntation하나로 처리하니까 깔끔해보여서 Data로 한거였는데, 찾아보니 마냥 좋은 방법이 아니네요~!

2021-07-05 14:09 UTC, Beoum commented on src/main/java/com/board/tddboard/domain/Comment.java
> +@Data
@Data anntation하나로 처리하니까 깔끔해보여서 Data로 한거였는데, 찾아보니 마냥 좋은 방법이 아니네요~!

2021-07-05 14:11 UTC, Beoum commented
이야기 해주신 피드백들 수정 완료했습니다.

2021-07-05 14:33 UTC, ohgillwhan commented
아쉬운 부분들을 좀 더 작성을 했읍니다. 아직 로직이 없는데 setter를 만드는것은 지양하도록 해보아요
그리고 최대한 최대한 setter는 없어야 합니다.

setter를 만드는것은 다른 개발자가 봤을때 무심코 사용하기 쉽고, 만약에 정말 필요해서 setter를 사용하더라도 set이라는 명칭보다는 change 등으로 다른 개발자들에게 경각심을 주는것도 나쁘지 않다고 생각합니다.

그리고 setter를 사용하게 되면은 비즈니스 로직에 결국 service로 빠지게 될것이고, 그러면 결국 어디서 변수가 수정되었는지 파악하기가 더 힘들어 집니다.

2021-07-05 14:41 UTC, ohgillwhan reviewed
.

2021-07-05 14:41 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/domain/Board.java
> +@Data
일반적으로 Data는 Getter, Setter, toString, hashcode, equals등을 구현을 할것인데, Board가 setter가 열리게 되면은 빈약한 모델이 되지 않을까?

2021-07-05 14:41 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/domain/Board.java
> +    private LocalDateTime deletedAt;
deletedAt이 라는게 있어보이는데, 이게 있으면 삭제되었다고 판단을 할것인지? 아니면 deleteAt같은것을 추가하여 삭제여부를 넣을것인지?

2021-07-05 14:41 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/service/impl/BoardServiceImpl.java
> +    public Board detail(Long id) {
함수는 기본적으로 동사로 시작하죠

2021-07-05 14:41 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/domain/Board.java
> +    @Getter @Setter
일단 비즈니스 로직을 만들지도 않았는데 setter를 먼저 만드는것은 빈약한 모델을 만들기 딱 좋을거같은데
setter를 먼저 작성하는것은 지양

2021-07-05 14:41 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/domain/Comment.java
> +    private LocalDateTime deletedAt;
삭제 여부는 어떻게 판단할지?

2021-07-05 14:43 UTC, Beoum commented on src/main/java/com/board/tddboard/domain/Board.java
> +    private LocalDateTime deletedAt;
deletedAt의 null 여부로 삭제 여부를 판단할 생각입니다.

2021-07-05 14:44 UTC, Beoum commented on src/main/java/com/board/tddboard/domain/Comment.java
> +    private LocalDateTime deletedAt;
deletedAt의 null 여부로 삭제 여부를 판단할 생각입니다.

2021-07-05 14:52 UTC, ohgillwhan commented
여기까지 진행하고, 다음 단계에서 더 보죠

2021-07-05 14:52 UTC, merged