feat: db연결 및 jpa설정, dao test code작성
Try-Tdd/board pull request #2
Opened 2021-07-06 15:05 UTC by Beoum

local db설정 및 jpa entity 설정. 추가로 BoardDao interface 구현체에 대한 test code 작성진행했습니다.

2021-07-07 02:27 UTC, ohgillwhan requested changes
리뷰 적었습니다.

2021-07-07 02:27 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/dao/impl/BoardDaoImpl.java
> +        int deleteResult = em.createQuery("DELETE FROM Board board WHERE board.id=:id")
Spring Data JPA를 쓰는데 왜 직접 쿼리를 사용해서 갖고오거나 삭제할까요?

2021-07-07 02:27 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/dao/impl/BoardDaoImpl.java
> +        int deleteResult = em.createQuery("DELETE FROM Board board WHERE board.id=:id")
BoardDaoImpl에 있는 다른 부분도 확인해봅시다.

2021-07-07 02:27 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/dao/impl/BoardDaoImpl.java
>  public class BoardDaoImpl implements BoardDao {
Spring Data JPA의 JPARepository를 알아봅시다

2021-07-07 02:27 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/dao/impl/BoardDaoImpl.java
> +        int updateResult = em.createQuery("UPDATE Board board SET board.title=:title, board.content=:content")
Spring Data JPA를 공부하고 작업하면 좋긴 할것 같아요.
JPA의 더티체킹도 알아보고요

2021-07-07 02:27 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/dao/impl/BoardDaoImpl.java
> +        int updateResult = em.createQuery("UPDATE Board board SET board.title=:title, board.content=:content")
결국 이렇게하면 쿼리를 직접 작성해야 하잖아요?
그러면 결국엔 데이터 집중쪽으로 빠질 가능성이 있어보여요.

2021-07-07 02:27 UTC, ohgillwhan commented on src/main/java/com/board/tddboard/domain/Board.java
> +@Builder
AllArgsConstructor와 Builder를 쓰면 validation해야할 필드들을 체크하기가 어려울거같은데요.
만약 title이 필수이면 객체 생성시에 Validation체크해야할 필요가 있는데, 지금과 같은 경우 builder를 쓰면 불가능하죠.

2021-07-07 02:27 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +@SpringBootTest
JPA만 테스트 할껀데 SpringBootTest까지 필요할까요?
@DataJpaTest 만으로도 충분해 보여요.

2021-07-07 02:27 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +@SpringBootTest
그리고 해당 어노테이션을 쓰면 @Transactional 어노테이션도 필요 없어집니다.

2021-07-07 02:27 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +    void 게시글작성() {
게시글 조회랑 틀린 부분이 뭘까요?

2021-07-07 02:27 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +    void 게시물조회() {
게시글 작성이랑 틀린 부분이 뭘까요?

2021-07-07 02:27 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        Board board = Board.builder()
이 부분은 계속 반복되네요? 어떻게 하면 없앨 수 있을까요?

2021-07-07 02:27 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        Board findBoard = boardDao.findById(saveBoard.getId());
위에서 save한 객체를 다시 쓰면 될거같은데, 어떻게 생각하세요?

2021-07-07 02:27 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        boolean passwordCompareResult = findBoard.getPassword().equals(saveBoard.getPassword());
이 부분이 조금 아쉽네요.
board에서 비밀번호를 직접 꺼내와서 처리해야 할까요?
board한테 너 이거 비밀번호 맞아? 라고 물어볼수도 있을거구요.

그리고 업데이트 할 때 처리도 가능하겠죠?
board에 업데이트 하는 함수를 만들고, 그 안에서 비밀번호를 체크한다음에 update를 할 수도 있을거에요.
그렇게 하면 throw new RuntimeException을 안해도 될거구요.

그리고 테스트 코드에서 throw를 던져야 할까요?

그러면 실제 API를 만들게 된다면 Exception은 생기지 않겠네요.

다시 생각해봐요.

2021-07-07 02:33 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        boolean passwordCompareResult = findBoard.getPassword().equals(saveBoard.getPassword());
디미터 법칙도 찾아봅시다
간단히 링크 남기는데, 이거 말고 더 찾아보고 싶으면 찾아봐요.

디미터 법칙을 사용하는 이유는 뭘지도 여기 댓글로 남겨줘요
https://johngrib.github.io/wiki/law-of-demeter/

2021-07-07 02:36 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +@SpringBootTest
https://cheese10yun.github.io/spring-boot-test/

2021-07-07 13:48 UTC, Beoum commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        Board board = Board.builder()
Board를 return 해주는 method를 따로 만들어서 처리 했습니다.

2021-07-07 13:49 UTC, Beoum commented on src/main/java/com/board/tddboard/domain/Board.java
> +@Builder
AllArgsConstructor와 Builder를 제거하고 생성자를 overloading해서 필수 값들을 넣어서 객체를 생성하도록 처리했습니다.

2021-07-07 14:06 UTC, Beoum commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +    void 게시글작성() {
게시글작성 test에서 검증부를 db에서 생성되는 id의 null check로 수정했습니다.

2021-07-07 14:06 UTC, Beoum commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +    void 게시물조회() {
게시글작성 test에서 검증부를 db에서 생성되는 id의 null check로 수정했습니다.

2021-07-07 14:44 UTC, Beoum commented on src/main/java/com/board/tddboard/dao/impl/BoardDaoImpl.java
> +        int deleteResult = em.createQuery("DELETE FROM Board board WHERE board.id=:id")
Spring Data JPA의 JPARepository를 적용해 쿼리 작성부분 제거했습니다.

2021-07-07 14:45 UTC, Beoum commented on src/main/java/com/board/tddboard/dao/impl/BoardDaoImpl.java
>  public class BoardDaoImpl implements BoardDao {
Spring Data JPA의 JPARepository를 적용했습니다.

2021-07-07 14:47 UTC, Beoum commented on src/main/java/com/board/tddboard/dao/impl/BoardDaoImpl.java
> +        int updateResult = em.createQuery("UPDATE Board board SET board.title=:title, board.content=:content")
board의 field에 hit라는 조회수 field가 추가 되면 관련 query들을 전부 수정줘야겠다는 생각이 들었고(많아지면 감당x).
그렇게 되면 ORM의 의미가 희석되고, 유지보수가 어려운 코드가 된다고 판단이 되어 query 제거하는 방향으로 작업 진행했습니다.

2021-07-07 14:53 UTC, Beoum commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        boolean passwordCompareResult = findBoard.getPassword().equals(saveBoard.getPassword());
리뷰 주신부분을 읽고 생각해보니 Dao test인데 비밀번호를 검증한다는건 데이터 접근 객체(Dao)의 역할과는 맞지 않는것 같아.
현재 test에서는 제거하고, 이후 Service test에 참고해서 작업하도록 하겠습니다.

2021-07-07 15:04 UTC, Beoum commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        boolean passwordCompareResult = findBoard.getPassword().equals(saveBoard.getPassword());
디미터 법칙은 캡슐화를 통해 객체 자신의 관심사와 그 외의 관심사(비즈니스, db 등)를 분리하고 효과적으로 코딩하기 위해 사용하는 것 같습니다.

2021-07-07 15:05 UTC, Beoum commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        Board findBoard = boardDao.findById(saveBoard.getId());
dirty checking 확인 후 해당 test 수정 진행했습니다.

2021-07-07 15:21 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        boolean passwordCompareResult = findBoard.getPassword().equals(saveBoard.getPassword());
디미터 법칙은 가장 가까운 이웃하고만 이야기 하는것인데, 그렇게 하면 함수가 수정될 경우 변경 포인트가 줄어들겠져

2021-07-07 15:37 UTC, ohgillwhan requested changes
테스트의 목적에 대해서 다시 생각해봅시다!

이게 정말 JPA 테스트까지 필요한것인지, 아니면 Domain 객체의 테스트만으로도 충분한지요.

2021-07-07 15:37 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +    private Board makeBoard() {
이러한 방법도 있을거고, @BeaforeEach도 찾아봅시당 그와 관련된것도 찾아보구요

2021-07-07 15:37 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        Board removeBoard = boardDao.save(saveBoard);
다시 save해야할까요? dirty checking 을 알아봅시다.

2021-07-07 15:37 UTC, ohgillwhan commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
>      void 게시물수정() {
이 테스트 코드는 무엇을 테스트 하려는걸까요?
Entity의 테스트일까요? JPA의 테스트일까요?

제가 보기에는 주 목적은 update하는곳에 있는데, 이러면 Entity의 테스트가 맞지 않을까요?

2021-07-07 15:54 UTC, Beoum commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
>      void 게시물수정() {
삭제 정책을 soft delete로 채택해서 해당 테스트를 추가했습니다. 하지만 이야기 해주신것 처럼 soft delete는 사실상 update와 같은 맥락으로 판단되어 게시물 삭제 test는 따로 없어도 될것 같습니다.

2021-07-07 15:56 UTC, ohgillwhan commented
이번 PR은 머지 진행하겠습니다~

남긴 리뷰는 다음 PR때 적용 해주세요.

그리고 이상하다고 남긴 부분 외에도, 비슷한 맥락의 이상한 부분은 수정해주세요 :D 

고생했습니다.

2021-07-07 15:56 UTC, merged

2021-07-10 12:56 UTC, Beoum commented on src/test/java/com/board/tddboard/dao/impl/BoardDaoImplTest.java
> +        Board removeBoard = boardDao.save(saveBoard);
dirty checking 확인 후 해당 test 수정 진행했습니다.