feat: boardSerivceImpl 구현 및 boardService test code 작성
Try-Tdd/board pull request #3
Opened 2021-07-08 14:41 UTC by Beoum

boardSerivceImpl 구현 및 boardService test code 작성 진행했습니다.

Dao test에서 미흡한 부분 수정 및 필요한 테스트 추가하였습니다.

2021-07-08 23:53 UTC, wook87 requested changes
고생하셨습니다. 코멘트 확인부탁드립니다.

2021-07-08 23:53 UTC, wook87 commented on src/main/java/com/board/tddboard/service/impl/BoardServiceImpl.java
>      public Board save(Board board) {
저장이 잘 되었는지 확인해주는 유효성검사를 도메인쪽에 넣어주는건 어떨까요?

2021-07-08 23:53 UTC, wook87 commented on src/main/java/com/board/tddboard/service/impl/BoardServiceImpl.java
> +        return boardDao.findById(id).get();
단순히 get하고 끝나버리면 null을 줄 수 있어요 null처리까지 해주는게 어떨까싶어요

2021-07-08 23:53 UTC, wook87 commented on src/main/java/com/board/tddboard/service/impl/BoardServiceImpl.java
> +        updateBoard.changeTitle(board.getTitle());
changeBoard의 성격으로 보이는데 board 객체를 넘기고 도메인내부에서 꺼내 넣게 이동하는건 어떨까요?

2021-07-08 23:53 UTC, wook87 commented on src/test/java/com/board/tddboard/service/BoardServiceTest.java
> +        return new Board("제목", "내용", "작성자", "1234");
static constructor로 객체 만드는게 어떨까싶어요
그리고 해당 메소드를 반복적으로 호출하고 있는데
'@BeforeClass' 로 한번만 호출하고 스태틱하게 쓰는건 어떨까요?

2021-07-08 23:53 UTC, wook87 commented on src/test/java/com/board/tddboard/service/BoardServiceTest.java
> +        assertThat(findBoard).isNotNull();
findBoard 를 extracting 해서 정확하게 원하는 게시글로 조회한게 맞는지 확인하는 로직을 넣는건 어떨까요?

2021-07-08 23:53 UTC, wook87 commented on src/test/java/com/board/tddboard/service/BoardServiceTest.java
> +        assertThat(result).isTrue();
제 개인적은 생각으로는 테스트에서는 jpa 영속성을 믿는게 아니라 정확하게 삭제되었는지 확인해주는게 필요하다고 생각합니다. jdbcTemplate으로 간단하게 해도 좋고 (이러려면 같은 트랜젹션에 있을수있게 데이터소스를 공유해야겠졈) 테스트용 레포지토리를 파는것도 좋구요

2021-07-09 13:12 UTC, Beoum commented on src/main/java/com/board/tddboard/service/impl/BoardServiceImpl.java
> +        return boardDao.findById(id).get();
null check하는 부분 추가했습니다.

2021-07-09 13:31 UTC, Beoum commented on src/main/java/com/board/tddboard/service/impl/BoardServiceImpl.java
> +        updateBoard.changeTitle(board.getTitle());
changeTitle, changeContent method를 제거하고 changeBoard method로 통합했습니다.

2021-07-09 14:00 UTC, Beoum commented on src/test/java/com/board/tddboard/service/BoardServiceTest.java
> +        return new Board("제목", "내용", "작성자", "1234");
@BeforeClass는 테스트 실행전 한번만 실행되는걸로 알고 있는데.
그렇게 되면 게시물 수정과 같이 게시물의 상태를 변경하는 테스트를 진행하게 되면 픽스쳐를 오염시켜 각각의 테스트에 영향을 줄 수 있겠다고 생각이 들어 @BeforeEach를 이용해 makeBoard method를 이용해서 각 테스트 전에 board객체를 초기화시켜주는 방향으로 수정했습니다.

2021-07-09 14:03 UTC, Beoum commented on src/test/java/com/board/tddboard/service/BoardServiceTest.java
> +        assertThat(findBoard).isNotNull();
null check와 더불어 (게시판 정책상)변경 할 수 없는 필드인 writer와 password를 이용한 검증 로직 추가했습니다.

2021-07-09 14:22 UTC, Beoum commented on src/main/java/com/board/tddboard/service/impl/BoardServiceImpl.java
>      public Board save(Board board) {
Board 도메인 안에 saveCheck라고 하는 return type이 boolean method를 만들어서 처리할까 생각이 들었지만,
그렇게 되면 도메인을 사용하는 로직에서, saveCheck에 의해 반환된 boolean 값을 이용해서 예외 처리를 다시 해줘야하는 문제가 생겨서(저장이 되지 않은 객체 자신의 문제를 다른 로직이 대신 처리해주는 상황은 맞지 않다고 생각이듭니다).
내부적으로 IllegalStateException을 발생하도록 수정했습니다.

2021-07-09 14:46 UTC, Beoum commented on src/test/java/com/board/tddboard/service/BoardServiceTest.java
> +        assertThat(result).isTrue();
리뷰 후 다시보니 작성한  test code 자체가 잘못되었다고 생각 됩니다.
해당 프로젝트에서는 soft delete를 정책으로하고 deletedAt field의 null 여부로 해당 데이터의 상태를 판단 하려고 했습니다.
하지만 해당 테스트는 실제적으로 삭제여부를 판단할 deletedAt field를 체크하지 않고. method의 return 값으로만 테스트를 진행했습니다.
그래서 Board 도메인 내부에  getDeletedAt보다 삭제여부를 확실히 알 수 있는 isRemoved method를 만들고 이에 맞춰 해당 테스트를 refactoring 진행했습니다.

2021-07-10 09:16 UTC, wook87 commented on src/test/java/com/board/tddboard/service/BoardServiceTest.java
> +        return new Board("제목", "내용", "작성자", "1234");
그렇다면, 픽스쳐는 아니네요 말씀대로 각각 테스트마다 호출되게 하는게 맞겠어요

2021-07-10 09:17 UTC, wook87 commented on src/main/java/com/board/tddboard/domain/Board.java
> +        if(board.getTitle() != null) {
이렇게 null을 회피하는것보다는 예외를 발생시키는게 어떨까요?

2021-07-10 12:51 UTC, Beoum commented on src/main/java/com/board/tddboard/domain/Board.java
> +        if(board.getTitle() != null) {
changeBoard의 호출시점에 title또는 content를 optional로 처리하고 싶어서 null을 회피하도록 한것인데.
method 이름 자체가 changeBoard인 만큼 변경가능한 부분은 전부 check 해야한다고 생각하시는 건지 의견 들어보고 싶습니다!

2021-07-10 14:28 UTC, wook87 commented on src/main/java/com/board/tddboard/domain/Board.java
> +        if(board.getTitle() != null) {
모든걸 그렇게 생각하는 것은 아니에요. 다만 바꾸지않은 행동을 취하면 왜 그런지에 대한 노티가 필요하지 않을까 싶었어요

2021-07-11 00:32 UTC, wook87 approved these changes

2021-07-11 10:36 UTC, merged